CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER'  -- USER or ADMIN
);

CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  city VARCHAR(80) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS cabs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  registration_no VARCHAR(40) UNIQUE NOT NULL,
  model VARCHAR(80) NOT NULL,
  city VARCHAR(80) NOT NULL,
  status VARCHAR(20) NOT NULL, -- AVAILABLE, ON_TRIP, INACTIVE
  driver_id BIGINT,
  FOREIGN KEY (driver_id) REFERENCES drivers(id)
);

CREATE TABLE IF NOT EXISTS rides (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  cab_id BIGINT,
  driver_id BIGINT,
  pickup VARCHAR(200) NOT NULL,
  dropoff VARCHAR(200) NOT NULL,
  city VARCHAR(80) NOT NULL,
  fare DECIMAL(10,2),
  status VARCHAR(20) NOT NULL, -- REQUESTED, ACCEPTED, ONGOING, COMPLETED, CANCELLED
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (cab_id) REFERENCES cabs(id),
  FOREIGN KEY (driver_id) REFERENCES drivers(id)
);